---
- name: CLUSTER - create vault storage directory
  ansible.builtin.file:
    path: "{{ vault_cluster_storage_path }}"
    state: directory
  register: vault_cluster_install_status

- name: CLUSTER - template the vault server config
  ansible.builtin.template:
    src: cluster-config.hcl.j2
    dest: "{{ vault_cluster_config_path }}"

- name: CLUSTER - start vault server
  community.docker.docker_container:
    name: vault-cluster
    state: started
    image: "{{ vault_image }}"
    command: vault server -config=/vault/config
    ports:
      - "{{ vault_cluster_port }}:{{ vault_cluster_port }}"
      - "{{ vault_cluster_cluster_port }}:{{ vault_cluster_cluster_port }}"
    volumes:
      - "{{ vault_cluster_storage_path }}:/vault/raft"
      - "{{ vault_cluster_config_path }}:/vault/config/config.hcl"
    capabilities:
      - IPC_LOCK
  become: true
