---
# tasks file for hashicorp-vault-cluster-role
- name: setup unsealer
  block:
    - name: import config-unsealer
      import_tasks: config-unsealer.yml

    - name: import init-unsealer
      import_tasks: config-unsealer.yml
      when: vault_unsealer_install_status.changed
  when: inventory_hostname in groups[unsealer_host_group_name]
  run_once: true  # forces the fact to be available on all hosts

- name: setup cluster
  block:
    - name: import config-cluster
      import_tasks: config-cluster.yml

    - name: import
      import_tasks: init-cluster.yml
      when: vault_cluster_install_status.changed
      run_once: true
  when: inventory_hostname in groups[cluster_hosts_group_name]
