---
- name: CREDENTIALS - vault unsealer
  debug:
    msg:
      - "Unseal Key 1: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_key_1'] }}"
      - "Unseal Key 2: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_key_2'] }}"
      - "Unseal Key 3: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_key_3'] }}"
      - "Unseal Key 4: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_key_4'] }}"
      - "Unseal Key 5: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_key_5'] }}"
      - "Root Token: {{ hostvars[groups[\
          vault_unsealer_inv_group_name][0]]['unsealer_token'] }}"
  run_once: true

- name: CREDENTIALS - vault cluster
  debug:
    msg:
      - "Recover Key 1: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_key_1'] }}"
      - "Recover Key 2: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_key_2'] }}"
      - "Recover Key 3: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_key_3'] }}"
      - "Recover Key 4: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_key_4'] }}"
      - "Recover Key 5: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_key_5'] }}"
      - "Root Token: {{ hostvars[groups[\
          vault_cluster_inv_group_name][0]]['cluster_token'] }}"
  run_once: true
